### ISSUE TITLE
no module named operators when import

### ISSUE THREAD

**Issue by jenuis** [maroba/findiff#12]
from findiff.operators import Plus, Minus, Operator, UnaryOperator, Multiply

ImportError: No module named operators

**Comment by jenuis** [comment]
You get the package name and file name the same. Also there are bugs in range. I'm using python2.7. After solving these problems. I got it run and have the right results. Thanks for sharing the work!

**Comment by maroba** [comment]
So far I only supported Python 3, but if your changes make it compatible with Python 2, great! Sorry for the delay, I was quite busy in the last weeks.

**Comment by jenuis** [comment]
I didn't run the test suits before. I just run the tests, yes, still complain about the import error!
