### ISSUE TITLE
float instead of integer in coefs.py

### ISSUE THREAD

**Issue by MehdiJenab** [maroba/findiff#15]
Error message:
"coefs.py", line 126, in _build_matrix
    A = [([1 for _ in range(-p, q+1)])]
TypeError: range() integer end argument expected, got float.

Solution that I am using:
I changed line 30, from:
num_central =  (2 * math.floor((deriv + 1) / 2) - 1 + acc)
to this:
num_central = int (2 * math.floor((deriv + 1) / 2) - 1 + acc)

it seems it is working, my code is as follows:

import coefs
coefs0 = coefs.coefficients(deriv=2, acc=2)

**Comment by maroba** [comment]
Is it possible that you are using Python 2 and not Python 3?
