### ISSUE TITLE
matrix representation doesn't work with order>2

### ISSUE THREAD

**Issue by Overnickel** [maroba/findiff#24]
Hi,

the matrix representation seems doesn't work when order larger than 2.
For instance, the below code will raise an error:
x = np.zeros((10))
d3_dx3 = FinDiff((0, 1, 3))
mat = d3_dx3.matrix(x.shape) 
print(mat.astype(int))

<img width="1265" alt="Screen Shot 2020-04-30 at 2 25 35 AM" src="https://user-images.githubusercontent.com/20069820/80678937-e2e48080-8a89-11ea-9635-c55aedbaf6c0.png">

**Comment by maroba** [comment]
Sorry for the late reply!
All right, there was a bug that should now be fixed. Version 0.8.1 is now available for installation with pip.
