### ISSUE TITLE
Recent release does not accept Numpy integers as parameters

### ISSUE THREAD

**Issue by vnmabus** [maroba/findiff#32]
It seems that you have added checks like `assert isinstance(order, int)` recently. This prevents using Numpy integers, such as `np.int32` which the code was able to handle before.

I suggest using `assert isinstance(order, numbers.Integral)` instead, and casting to `int` afterwards if you truly need to use that type (probably not).

**Comment by maroba** [comment]
You are right, I didn‘t think of people using numpy integers. I will fix it shortly.

**Comment by maroba** [comment]
Ok, I changed it, and released v0.8.7 on pypi.

**Comment by vnmabus** [comment]
I can confirm that the new version fixes this.
