### ISSUE TITLE
Recent release does not accept 0 order

### ISSUE THREAD

**Issue by vnmabus** [maroba/findiff#33]
As with in #32, the recent release has an assert checking that the order is positive. 0 order derivatives (that is, do not derive for that dimension) were accepted before.

My suggestion is to change the assert to check only that the order is nonnegative.

**Comment by maroba** [comment]
Same as #32, I didn‘t consider this use case. I‘ll change it.

**Comment by maroba** [comment]
Ok, I changed it, and released v0.8.7 on pypi.

**Comment by vnmabus** [comment]
Ok, the new version fixes this.
