### ISSUE TITLE
Feature request: Generate coefficients from offset specification

### ISSUE THREAD

**Issue by rdaly525** [maroba/findiff#34]
Very cool package!

I have a use case where I want to specify the offsets directly to generate the coefficients similar to https://web.media.mit.edu/~crtaylor/calculator.html.

Is there a way to do something along the lines of:
`coefs = findiff.coefficients(deriv=2, offsets=[-3,-2,-1,0,1], symbolic=True)`

Thanks!

**Comment by maroba** [comment]
Thanks for the request!

I have implemented the feature and deployed a version 0.8.8 to PyPi.

**Comment by rdaly525** [comment]
Awesome!! Just tried it out and it works great! Thanks for implementing this.
