### ISSUE TITLE
Math equations in README are unreadable in Github dark mode

### ISSUE THREAD

**Issue by kkiningh** [maroba/findiff#35]
When Github darkmode is turned on (Settings > Appearance > Dark) the equations in the README are nearly impossible to read. For example: 
![screenshot](https://user-images.githubusercontent.com/360345/106399641-cab1e100-63ce-11eb-954c-a88cafd2133e.png)

Thanks for creating this package!

**Comment by maroba** [comment]
Oh, I didn't know that github offers that feature. I will change the background of the images from transparent to white...

**Comment by maroba** [comment]
Should be solved now.
