### ISSUE TITLE
ModuleNotFoundError: No module named 'findiff'

### ISSUE THREAD

**Issue by secco88** [maroba/findiff#39]
c:\...\trendln\__init__.py in get_extrema(h, extmethod, accuracy)
    434     elif extmethod == METHOD_NUMDIFF:
    435         #pip install findiff
--> 436         from findiff import FinDiff
    437         dx = 1 #1 day interval
    438         d_dx = FinDiff(0, dx, 1, acc=accuracy) #acc=3 #for 5-point stencil, currenly uses +/-1 day only

ModuleNotFoundError: No module named 'findiff'

package findiff  is correctly installed, what can I do?

**Comment by maroba** [comment]
Are you sure that you have installed findiff to the correct environment? 

Did you install findiff using pip in a virtual environment or systemwide? Or did you install using setup.py based on the code?

**Comment by secco88** [comment]
I have installed it both in env and in the system but the problem persists
