### ISSUE TITLE
Adding findiff to conda-forge

### ISSUE THREAD

**Issue by tnigon** [maroba/findiff#41]
Hi! Great package. I have a package [hs-process](https://github.com/tnigon/hs_process) that has a dependency on findiff. I need to keep my package up to date on Anaconda, and that means all dependencies must be available there as well. I will go ahead and add the latest version of this package to [conda-forge](https://conda-forge.org/), but I would like to list you (@maroba) as a maintainer (as well as myself). Once I get the conda-forge recipe started, I will need you to comment saying you are willing to be a maintainer. I will add a comment here with a link to notify you of this.

Thanks, let me know if you have any questions!

**Comment by tnigon** [comment]
If you're willing, please comment at this [pull request](https://github.com/conda-forge/staged-recipes/pull/14579) stating you are willing to be listed as a maintainer. If not, I can remove your name from that section. Thanks again!

**Comment by maroba** [comment]
Sorry, I was busy with other topics last week.

Yes, you can list be as maintainer.

**Comment by tnigon** [comment]
@maroba - thank you. You should see an invitation to join the conda-forge feedstock organization and should now be listed as a maintainer for [findiff](https://github.com/conda-forge/findiff-feedstock).
