### ISSUE TITLE
Allow the user to specify difference method

### ISSUE THREAD

**Issue by MauroVA98** [maroba/findiff#50]
Instead of FinDiff using central coefficients whenever possible and switching to backward or forward coefficients if not enough points are available on either side, allow the user to specify a desired method.

**Comment by maroba** [comment]
So, you basically want to apply the differential operator only at single points instead of the whole grid? Otherwise prescribing the method would not work on at least some part of the grid...

**Comment by MauroVA98** [comment]
Let's say I have velocity measurements and I want to differentiate them to get accelerations, technically I only have the previous measurements for velocity at any given time-step therefore I would like to apply backward differentiation only.

**Comment by ColinMoldenhauer** [comment]
Has this been implemented or is still TODO? From looking at the source code, I still can't seem to find a way to specify the default difference direction for the interior.
