### ISSUE TITLE
Replace math images by latex expressions

### ISSUE THREAD

**Issue by maroba** [maroba/findiff#65]
Github *finally* supports math expressions in markdown.:

https://github.blog/2022-05-19-math-support-in-markdown/

Replace all math images in README.md by corresponding Latex expressions.

**Comment by js-808** [comment]
Just commenting to ensure I'm not duplicating anyone else's work - I'm happy to take on this issue if nobody else is working on it!

**Comment by maroba** [comment]
@js-808 Feel free to work on this issue.
