### ISSUE TITLE
Analytic inversion of Vandermonde matrix

### ISSUE THREAD

**Issue by dwierichs** [maroba/findiff#66]
Hi, new fan of this package! :)

I was wondering: At least within the applications I'm looking at, the equation solving performed in [L99 of coefs.py](https://github.com/maroba/findiff/blob/663162c908a5e168e7ea95778cd14df9acd7bafa/findiff/coefs.py#L99) (or L89 for `symbolic=True`) can also be done analytically, because `matrix` is a [Vandermonde matrix](https://en.wikipedia.org/wiki/Vandermonde_matrix), and computing specific elements of its inverse is doable without any matrix inversion (see for example [ProofWiki](https://proofwiki.org/wiki/Inverse_of_Vandermonde_Matrix)).
Would this be interesting to implement? I noticed that `findiff.coefficients` becomes unstable at some point (admittedly for quite large values of `acc~25`).

Thanks for the good work, kind regards!

**Comment by maroba** [comment]
Now that I'm thinking about it, using the direct solution without solving the system, as you proposed initially, may also solve the stability issue. That would make the readability argument less important. So, I think it's worth a try!

**Comment by dwierichs** [comment]
Hey @maroba,
thanks for the quick reply!
Yeah I definitely agree that the equation solver is more readable and maintainable :)
Indeed my thought was that the direct computation could be more stable, but if the trick of doing stuff symbolically and then  converting back is stable as well, that might actually be the nicer path (even if not optimal computationally, but as you say, that doesn't really matter).

**Comment by maroba** [comment]
@dwierichs 
I'm working on some other topic right now. So if you would like to implement it yourself, feel free to do so. If you need help finding orientation in the code, just tell me.

**Comment by maroba** [comment]
Closed with PR #67
