### ISSUE TITLE
Outdated conda-forge builds

### ISSUE THREAD

**Issue by ma-sadeghi** [maroba/findiff#68]
The latest PyPI build is v9.2.0, but the conda-forge build is v0.8.9

**Comment by maroba** [comment]
I only maintain the package on pip so far. The conda version was uploaded by someone else. I have reached out to the guy to  update it and share the maintenance with me.

**Comment by og113** [comment]
This issue has been fixed recently.
- https://anaconda.org/conda-forge/findiff
- https://github.com/conda-forge/findiff-feedstock
