### ISSUE TITLE
How are the higher order derivatives computed in your code?

### ISSUE THREAD

**Issue by argha004** [maroba/findiff#71]
Hello, I'm interested in understanding how your code implements higher order derivatives in 3D. I wasn't able to find a white paper or documentation explaining the details of your implementation, so I was hoping you could provide some insight before I use your code.

In my own code, I've been implementing finite differences recursively to compute fourth order derivatives of a scalar function in 3D. However, I've been experiencing significant errors due to the recursive nature of the implementation. So, I'm curious if you've a similar approach to compute the higher order derivatives.

**Comment by maroba** [comment]
Hi,

in the 1D-case the standard stencils are computed from a Taylor expansion, and in multiple dimensions, the standard stencils are superpositions of the 1D stencils extended to several axes. The theory is described on [this page](https://findiff.readthedocs.io/en/latest/source/theory.html). Does that help you?

Best regards,
Matthias
