### ISSUE TITLE
Input for non-uniform spacing

### ISSUE THREAD

**Issue by IamJYC** [maroba/findiff#77]
HI,

Thank you very much for the very helpful package. I was wondering when inputting non-uniform spacing if I should use the coordinates of x (the independent variable) or dx (say x.diff()). Thank you very much!

Cheers,

**Comment by maroba** [comment]
@IamJYC For nonuniform grids, you give the coordinates instead of spacing. Here is an [example](https://findiff.readthedocs.io/en/latest/source/examples-non-uniform-grids.html) (at the bottom of the page).

**Comment by IamJYC** [comment]
Thank you for your prompt response!

**Comment by IamJYC** [comment]
> @IamJYC For nonuniform grids, you give the coordinates instead of spacing. Here is an [example](https://findiff.readthedocs.io/en/latest/source/examples-non-uniform-grids.html) (at the bottom of the page).

Thank you for your prompt response!
