### ISSUE TITLE
possible typo in theory section

### ISSUE THREAD

**Issue by YannickRuske** [maroba/findiff#80]
Hi,
I might be mistaken here, bit I think the theory page (https://github.com/maroba/findiff/blob/master/docs/source/theory.rst) contains a typo in the Kronecker delta.
To give the desired result of $f_k^{(n)}$ it should be $\delta_{n \alpha}$ instead of $\delta_{k \alpha}$ (which would give $f_k^{(k)}$).

(Also, do you have a reference regarding the claim made in the last line regarding optimal stencils in higher dimensions being the sum of 1D stencils?)

Best regards

**Comment by maroba** [comment]
You are right, that's a typo! Do you want to send a pull request (so that you can be a contributor)? If not, I can fix it quickly myself. Regarding the claim, I think I had a reference, but I have to dig it out.

**Comment by YannickRuske** [comment]
Feel free to fix it yourself, it's just a small typo after all.
If it's not too much work I'd love to take a look at that reference.
