### ISSUE TITLE
`FinDiff.set_accuracy` does not support multivariables

### ISSUE THREAD

**Issue by n-takumasa** [maroba/findiff#86]
**Describe the bug**
see reproduce

**To Reproduce**

```python
>>> import findiff
>>> findiff.__version__
'0.10.2'
>>> findiff.FinDiff((0, 1)).set_accuracy(1)  # OK
>>> findiff.FinDiff((0, 1), (1, 1)).set_accuracy(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "findiff\operators.py", line 114, in set_accuracy
    self.pds.set_accuracy(acc)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mul' object has no attribute 'set_accuracy'
```

**Expected behavior**
No error raised

**Desktop (please complete the following information):**
 - OS: Windows11
 - Version: 23H2

**Additional context**
I think this is the cause.
https://github.com/maroba/findiff/blob/6e602aa906ae4923ff72f168e1779145b1699022/findiff/operators.py#L146-L147
To be able to change `acc` later, it would be necessary to traverse the entire syntax tree, which seems like a lot of work.

**Comment by maroba** [comment]
Hi, thanks for reporting!

I have refactored the code. Now it should work (version 0.11.0).

Note however, that only even accuracy orders are supported (unless you define the stencil manually).

**Comment by maroba** [comment]
@n-takumasa Please re-open if it is not working as expected.
